
ynfciltkzptrsmrjylkd = "https://ynfciltkzptrsmrjylkd.supabase.co"

[functions.convert-pdf-to-images]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.process-saps-document]
verify_jwt = true

[auth.email]
enable_mfa = true
