// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynfciltkzptrsmrjylkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluZmNpbHRrenB0cnNtcmp5bGtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MTM2MTIsImV4cCI6MjA1OTE4OTYxMn0.cutwDg5CR6AL_cZWLIXnjah4lOj8FOWyotxj9d7qZpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);